name: personalized-news-feed-web-app
services:
  MongoDB1:
    image: mongo:6.0.13
    container_name: MongoDB1
    restart: always
    networks:
      - mongo-network
    ports:
      - 27017:27017
    depends_on:
      - MongoDB2
    links:
      - MongoDB2
    volumes:
      - MongoDB.Data:/data/db
      - ./scripts/rs-init.sh:/scripts/rs-init.sh
      - ./scripts/init.js:/scripts/init.js
    entrypoint: ['/usr/bin/mongod', '--bind_ip_all', '--replSet', 'dbrs']
  MongoDB2:
    image: mongo:6.0.13
    container_name: MongoDB2
    restart: always
    networks:
      - mongo-network
    ports:
      - 27018:27017
    entrypoint: ['/usr/bin/mongod', '--bind_ip_all', '--replSet', 'dbrs']

networks:
  mongo-network:
    driver: bridge

volumes:
  MongoDB.Data:
